"""
Attention!!! This is a Redis-based queue implementation [Generated by Cursor]
"""

import redis
import json
import time
import logging
from typing import Any, Optional
from queue import Empty


class RedisQueue:
    """
    Redis-based queue implementation
    """

    def __init__(
        self,
        queue_name: str,
        redis_host: str = "localhost",
        redis_port: int = 6379,
        redis_db: int = 0,
        timeout: int = 10,
        logger: Optional[logging.Logger] = None,
    ):
        """
        Initialize Redis queue

        Args:
            redis_host: Redis server host
            redis_port: Redis server port
            redis_db: Redis database number
            queue_name: Name of the Redis list to use as queue
            timeout: Default timeout for get operations
            logger: Optional logger instance
        """
        self.redis_client = redis.Redis(
            host=redis_host, port=redis_port, db=redis_db, decode_responses=False
        )
        self.queue_name = queue_name
        self.timeout = timeout
        self.logger = logger or logging.getLogger(__name__)

        # Test connection
        try:
            self.redis_client.ping()
            self.logger.info(f"Connected to Redis at {redis_host}:{redis_port}")
        except redis.ConnectionError as e:
            self.logger.error(f"Failed to connect to Redis: {e}")
            raise e

    def put(self, item: Any) -> None:
        try:
            serialized_item = json.dumps(item, default=self._json_serializer)
            self.redis_client.lpush(self.queue_name, serialized_item)
        except Exception as e:
            self.logger.error(f"Failed to put item into queue: {e}")
            raise e

    def get(self, timeout: Optional[int] = None) -> Any:
        timeout = timeout or self.timeout

        try:
            # blocking pop from right side of list (FIFO)
            result = self.redis_client.brpop(self.queue_name, timeout=timeout)

            if result is None:
                raise Empty("Queue timeout")

            # result is a tuple: (queue_name, item)
            _, serialized_item = result
            item = json.loads(
                serialized_item.decode("utf-8"), object_hook=self._json_deserializer
            )
            return item

        except redis.TimeoutError:
            raise Empty("Queue timeout")
        except Exception as e:
            self.logger.error(f"Failed to get item from queue: {e}")
            raise

    def qsize(self) -> int:
        try:
            return self.redis_client.llen(self.queue_name)
        except Exception as e:
            self.logger.error(f"[{__name__}] Failed to get queue size: {e}")
            return 0

    def empty(self) -> bool:
        return self.qsize() == 0

    def close(self) -> None:
        try:
            self.redis_client.close()
            self.logger.info(f"[{__name__}] Redis connection closed")
        except Exception as e:
            self.logger.error(f"[{__name__}] Error closing Redis connection: {e}")
            
            
    def command(self, command: str) -> Any:
        try:
            return self.redis_client.execute_command(command)
        except Exception as e:
            self.logger.error(f"[{__name__}] Error executing Redis command: {e}")
            raise

    def _json_serializer(self, obj: Any) -> Any:
        """
        Custom JSON serializer for handling special types
        """
        if isinstance(obj, bytes):
            # Convert bytes to base64 string for JSON serialization
            import base64

            return {"__bytes__": base64.b64encode(obj).decode("utf-8")}
        elif hasattr(obj, "__dict__"):
            return {"__object__": obj.__dict__, "__class__": obj.__class__.__name__}
        else:
            raise TypeError(f"Object of type {type(obj)} is not JSON serializable")

    def _json_deserializer(self, obj: dict) -> Any:
        """
        Custom JSON deserializer for handling special types
        """
        if isinstance(obj, dict):
            if "__bytes__" in obj:
                import base64

                return base64.b64decode(obj["__bytes__"])
            elif "__object__" in obj and "__class__" in obj:
                class_name = obj["__class__"]
                obj_dict = obj["__object__"]
                return obj_dict
        return obj


def create_redis_queue(
    queue_name: str,
    redis_host: str = "localhost",
    redis_port: int = 6379,
    redis_db: int = 0,
    timeout: int = 8,
    logger: Optional[logging.Logger] = None,
) -> RedisQueue:
    assert queue_name is not None, "queue_name is required"
    return RedisQueue(
        redis_host=redis_host,
        redis_port=redis_port,
        redis_db=redis_db,
        queue_name=queue_name,
        timeout=timeout,
        logger=logger,
    )
