#!/bin/bash
# emu_start_544545535355_sfdze1.sh <logname> [extra emulate args...]
# Auto-generated by scripts/ida/stage_emulator_ta.py (mirrors emu_start_sfdze1.sh).
# Loads the SHIPPING-build TA staged at teegris/tas/544545535355_sfdze1/ instead of the
# bundled S9BYH2 corpus binary. The UUID-named file inside the subdir keeps the
# emulator's filename<->TEEC-OpenSession UUID check happy.
set -u
LOG="$1"
shift 1
EXTRA="$*"
UUID="00000000-0000-0000-0000-544545535355"
SUB="544545535355_sfdze1"
REPO=/home/lamb/opt/TA_GP_emulator
LOGREL="teegris/confirmations/_logs/${LOG}.log"

docker rm -f emu >/dev/null 2>&1
: > "${REPO}/${LOGREL}"

docker run -d --rm --name emu --network host \
  -v "${REPO}":/srv -w /srv/emulator \
  -v /dev/shm:/dev/shm --ipc=host --shm-size=100g \
  ta_emu bash -c "cp ../teegris/tas/${SUB}/${UUID}.ta rootfs/ && cp ../teegris/tas/${SUB}/${UUID}.json rootfs/ && exec python3 -m emulate rootfs/${UUID}.ta --fuzz_harness /dev/null ${EXTRA} > /srv/${LOGREL} 2>&1" >/dev/null

for i in $(seq 1 60); do
  if ! docker ps --format '{{.Names}}' | grep -q '^emu$'; then
    echo "EMU_DIED after ${i}s"; tail -30 "${REPO}/${LOGREL}"; exit 1
  fi
  if ss -ltn 2>/dev/null | grep -q ':1337'; then
    echo "EMU_READY after ${i}s (544545535355_sfdze1, log=${LOGREL})"; exit 0
  fi
  sleep 1
done
echo "EMU_TIMEOUT (no :1337 after 60s)"; tail -30 "${REPO}/${LOGREL}"; exit 1
